on:
  push:
jobs:
  build:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    runs-on: nomadtools mem=1024 memmax=1234 cpu=100
    steps:
      - uses: actions/checkout@v4
      - run: echo Hello, world!
      - run: docker version
      - run: docker run --rm alpine echo hello world
      - run: sleep 60
