on:
  push:
  pull_request:
jobs:
  build1G:
    runs-on: nomadtools mem=1000
    steps:
      - run: id
      - uses: actions/checkout@v4
      - run: docker info
      - run: stat /var/lib/docker
      - run: docker run --rm ${{matrix.image}} echo hello world ${{matrix.times}}
      - run: sleep $((RANDOM % 200))
