on:
  push:
jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu, alpine, archlinux]
        times: [1, 2, 3]
    runs-on: nomadtools mem=1024 memmax=1234 cpu=100
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm ${{matrix.image}} echo hello world ${{matrix.times}}
  pipcache:
    runs-on: nomadtools
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        times: [1, 2, 3]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install pandas
