on:
  push:
jobs:
  build:
    runs-on: nomadtools mem=1024 memmax=1234 cpu=100
    steps:
      - uses: actions/checkout@v4
      - run: echo Hello, world!
      - run: docker version
      - run: docker run -ti --rm alpine echo hello world
      - run: sleep 60
